#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hyperscan
Version  : 5.1.0
Release  : 8
URL      : https://github.com/intel/hyperscan/archive/v5.1.0.tar.gz
Source0  : https://github.com/intel/hyperscan/archive/v5.1.0.tar.gz
Summary  : A high-performance multiple regex matching library, commonly used with suricata or snort.
Group    : Development/Tools
License  : BSD-3-Clause Intel
Requires: hyperscan-lib = %{version}-%{release}
Requires: hyperscan-license = %{version}-%{release}
BuildRequires : Sphinx
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : ragel

%description
Hyperscan Example Code
======================
The files in this directory contain example code demonstrating the use of the
Hyperscan regular expression matching library. The examples have been
constructed to be useful utility programs, but they have been simplified
somewhat, so generally contain "shortcuts" that one would not take if building
a "real" system.

%package dev
Summary: dev components for the hyperscan package.
Group: Development
Requires: hyperscan-lib = %{version}-%{release}
Provides: hyperscan-devel = %{version}-%{release}

%description dev
dev components for the hyperscan package.


%package doc
Summary: doc components for the hyperscan package.
Group: Documentation

%description doc
doc components for the hyperscan package.


%package lib
Summary: lib components for the hyperscan package.
Group: Libraries
Requires: hyperscan-license = %{version}-%{release}

%description lib
lib components for the hyperscan package.


%package license
Summary: license components for the hyperscan package.
Group: Default

%description license
license components for the hyperscan package.


%prep
%setup -q -n hyperscan-5.1.0
pushd ..
cp -a hyperscan-5.1.0 buildavx2
popd
pushd ..
cp -a hyperscan-5.1.0 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549126045
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export CFLAGS="$CFLAGS -O3 -march=haswell "
export FCFLAGS="$CFLAGS -O3 -march=haswell "
export FFLAGS="$CFLAGS -O3 -march=haswell "
export CXXFLAGS="$CXXFLAGS -O3 -march=haswell "
export CFLAGS="$CFLAGS -march=haswell -m64"
export CXXFLAGS="$CXXFLAGS -march=haswell -m64"
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx512
pushd clr-build-avx512
export CFLAGS="$CFLAGS -O3 -march=skylake-avx512 "
export FCFLAGS="$CFLAGS -O3 -march=skylake-avx512 "
export FFLAGS="$CFLAGS -O3 -march=skylake-avx512 "
export CXXFLAGS="$CXXFLAGS -O3 -march=skylake-avx512 "
export CFLAGS="$CFLAGS -march=skylake-avx512 -m64 "
export CXXFLAGS="$CXXFLAGS -march=skylake-avx512 -m64 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1549126045
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/hyperscan
cp COPYING %{buildroot}/usr/share/package-licenses/hyperscan/COPYING
cp LICENSE %{buildroot}/usr/share/package-licenses/hyperscan/LICENSE
pushd clr-build-avx512
%make_install_avx512  || :
popd
pushd clr-build-avx2
%make_install_avx2  || :
popd
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/hs/hs.h
/usr/include/hs/hs_common.h
/usr/include/hs/hs_compile.h
/usr/include/hs/hs_runtime.h
/usr/lib64/haswell/avx512_1/libhs.so
/usr/lib64/haswell/libhs.so
/usr/lib64/haswell/libhs_runtime.so
/usr/lib64/libhs.so
/usr/lib64/libhs_runtime.so
/usr/lib64/pkgconfig/libhs.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/hyperscan/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/avx512_1/libhs.so.5
/usr/lib64/haswell/avx512_1/libhs.so.5.1.0
/usr/lib64/haswell/libhs.so.5
/usr/lib64/haswell/libhs.so.5.1.0
/usr/lib64/haswell/libhs_runtime.so.5
/usr/lib64/haswell/libhs_runtime.so.5.1.0
/usr/lib64/libhs.so.5
/usr/lib64/libhs.so.5.1.0
/usr/lib64/libhs_runtime.so.5
/usr/lib64/libhs_runtime.so.5.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/hyperscan/COPYING
/usr/share/package-licenses/hyperscan/LICENSE
